# Generated by Django 3.2 on 2023-10-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_delete_followauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
